<?php
/**
 * Created by PhpStorm.
 * User: zhangzenan
 * Date: 2017/8/1
 * Time: 11:55
 */

namespace app\controllers;


use app\config\AppConfig;
use app\models\Banner;
use common\services\RedisService;
use common\services\TokenService;

class BannerController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 获得所有Banner
     */
    public function actionGetAllBanners()
    {
        $result = Banner::find()->all();
        if (count($result) == 0) {
            return ['ret' => -1, 'msg' => '没有数据'];
        }
        return $this->renderJSON(0, 'success', $result);
    }

    public function actionTest(){
        $ret = RedisService::hGet(AppConfig::uid2token, '1');
        var_dump($ret);
//        RedisService::hSet('test', '111', 1);
//        $ret = RedisService::hGet('test', '111');
//        var_dump($ret);
        exit;
    }

}