<?php
/**
 * Created by PhpStorm.
 * User: zhangzenan
 * Date: 2017/8/1
 * Time: 11:54
 */

namespace app\controllers;


use app\filters\DataFilter;
use common\services\LogService;
use yii\web\Controller;
use yii\web\Response;

class BaseController extends Controller
{
    public $enableCsrfValidation = false;

    const pageSize = 10;

    const pageSize2 = 20;

    public $postData = null;

    public $token = null;

    public function behaviors()
    {
        return [
            [
                'class' => DataFilter::className(),
            ]
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
//        \Yii::$app->getResponse()->format = 'json';
    }

    public function beforeAction($action)
    {
        $this->log('action:' . $action->id . ' before action | req data:' . json_encode($this->postData));
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        $this->log('result:' . json_encode($result, JSON_UNESCAPED_UNICODE));
        $this->log('action' . $action->id . ' after action');
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    public function json($data){
        \Yii::$app->response->format = Response::FORMAT_JSON;
        \Yii::$app->response->setStatusCode(200);
        \Yii::$app->response->data = $data;
        return $data;
    }

    public function response($ret, $msg, $data=array()){
        if(empty($data)){
            $data = new \stdClass();
        }
        return $this->json([
            'ret' => $ret,
            'msg' => $msg,
            'data' => $data,
        ]);
    }

    /**
     * 写日志
     * @param $msg
     */
    public function log($msg)
    {
        $logInfo = is_string($msg) ? $msg : json_encode($msg, JSON_UNESCAPED_UNICODE);
        LogService::log($logInfo, \Yii::$app->controller->id);
    }

    protected function renderJSON($code, $msg, $data = '')
    {
        return [
            'ret' => $code,
            'msg' => $msg,
            'data' => $data
        ];
    }

}