<?php
/**
 * Created by PhpStorm.
 * User: zhangzenan
 * Date: 2018/4/16
 * Time: 22:06
 */
namespace app\controllers;
use common\services\AlipayService\AlipayService;
use common\services\AlipayService\AlipayTradeAppPayRequest;
use common\services\AlipayService\AopClient;


/**
 * 支付网关服务
 * Class PayGatewayController
 * @package app\controllers
 */
class PayGatewayController extends BaseController
{
    /**@var AlipayService $alipayService**/
    private $alipayService = null;

    public function init()
    {
        $this->alipayService = new AlipayService();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionGetPayInfo(){
        $this->alipayService->createPayOrder(123);
    }
}