<?php
/**
 * Created by PhpStorm.
 * User: zhangzenan
 * Date: 2018/2/15
 * Time: 12:26
 */

namespace app\controllers;


use app\filters\UserFilter;
use app\models\Products;
use common\services\QiniuService;
use common\services\RedisService;
use yii\db\Exception;

class UserProductController extends BaseController
{
    public function behaviors()
    {
        return [
            [
                'class' => UserFilter::className(),
            ]
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 添加商品(包括图片)
     */
    public function actionPublishProduct()
    {
        $params = $this->postData;
        $uid = RedisService::getUidByToken($this->token);

        $transaction = Products::getDb()->beginTransaction();
        try {
            $product = new Products();
            $product->FstrProductName = $params['productName'];
            $product->FstrDetails = $params['productDetail'] ?: '';
            $product->FstrDescription = $params['description'] ?: '';
            $product->FuiBuyPrice = $params['buyPrice'] ?: 0;
            $product->FuiRentPrice = $params['rentPrice'] ?: 0;
            $product->FuiUserId = $uid;
            $product->FuiNum = $params['FuiNum'] ?: 1;
            $product->FuiCreateTime = time();
            $product->FuiCanRent = $params['FuiCanRent'] ? $params['FuiCanRent'] : 0;
            $product->FuiAtLeastDays = $params['FuiAtLeastDays'] ? $params['FuiAtLeastDays'] : 0;
            $product->FuiBrandId = $params['FuiBrandId'] ? $params['FuiBrandId'] : 0;

            if (!$product->save()) {
                return $this->renderJSON(-1004, '添加商品失败');
            }
            $transaction->commit();
            return $this->renderJSON(0, 'ok');
        } catch (Exception $e) {
            $transaction->rollBack();
            return $this->renderJSON($e->getCode(), $e->getMessage());
        }
    }

    /**
     * 收藏商品
     */
    public function actionCollectProducts()
    {
        $data = \Yii::$app->request->post();
        $productId = $data['pid'];
        $uid = $data['uid'];
        if (!$productId || !$uid) {
            return $this->renderJSON(-1000, 'invalid params');
        }
        $user = User::find()->select('FuiUserId')
            ->where(['FuiUserId' => $uid])->asArray()->one();
        if (empty($user)) {
            return $this->renderJSON(-1001, 'user not exist');
        }
        $productCollection = new ProductCollection();
        $productCollection->FuiUserId = $uid;
        $productCollection->FuiProductId = $productId;
        $productCollection->FuiCreateTime = time();
        if (!$productCollection->save()) {
            return $this->renderJSON(-1002, '收藏失败');
        }
        return $this->renderJSON(0, 'success');
    }

}