<?php
/**
 * Created by PhpStorm.
 * User: zhangzenan
 * Date: 2018/2/15
 * Time: 12:26
 */

namespace app\controllers;


use app\filters\UserFilter;
use app\models\Products;
use common\services\QiniuService;
use common\services\RedisService;
use yii\db\Exception;

class UserProductController extends BaseController
{
    public function behaviors()
    {
        return [
            [
                'class' => UserFilter::className(),
            ]
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 添加商品(包括图片)
     */
    public function actionPublishProduct()
    {
        $params = $this->postData;
        $uid = RedisService::getUidByToken($this->token);

        $transaction = Products::getDb()->beginTransaction();
        try {
            $service = new QiniuService();
            $productPhoto = json_decode($params['productPhoto'], true);
            $productsUrl = [];
            foreach ($productPhoto as $v) {
                $fileName = uniqid() . $v['name'];
                $result = $service->upload($fileName, $v['value']);
                if ($result['ret'] == 0) {
                    $url = $result['data']['url'];
                    $productsUrl[] = $url;
                } else {
                    throw new Exception('图片上传失败', -1003);
                }
            }

            $product = new Products();
            $product->FstrProductName = $params['FstrProductName'];
            $product->FstrDetails = $params['FstrDetails'] ? $params['FstrDetails'] : '';
            $product->FstrDescription = $params['FstrDescription'] ? $params['FstrDescription'] : '';
            $product->FuiBuyPrice = $params['FuiBuyPrice'] ? $params['FuiBuyPrice'] : 0.00;
            $product->FuiRentPrice = $params['FuiRentPrice'] ? $params['FuiRentPrice'] : 0.00;
            $product->FuiUserId = $uid;
            $product->FuiNum = $params['FuiNum'] ? $params['FuiNum'] : 1;
            $product->FuiCreateTime = time();
            $product->FuiCanRent = $params['FuiCanRent'] ? $params['FuiCanRent'] : 0;
            $product->FuiAtLeastDays = $params['FuiAtLeastDays'] ? $params['FuiAtLeastDays'] : 0;
            $product->FuiBrandId = $params['FuiBrandId'] ? $params['FuiBrandId'] : 0;
            $product->FstrPhotoUrl = json_encode($productsUrl);

            if (!$product->save()) {
                return $this->renderJSON(-1004, '添加商品失败');
            }
            $transaction->commit();
            return $this->renderJSON(0, 'ok');
        } catch (Exception $e) {
            $transaction->rollBack();
            return $this->renderJSON($e->getCode(), $e->getMessage());
        }
    }

}