<?php
/**
 * Created by PhpStorm.
 * User: zhangzenan
 * Date: 2018/1/23
 * Time: 20:05
 */

namespace app\filters;


use app\controllers\BaseController;
use app\utils\Util;
use common\services\RedisService;

class DataFilter extends BaseFilter
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        $data = \Yii::$app->request->post()?:json_decode(file_get_contents("php://input"),true);
        /** @var BaseController $c */
        $c = \Yii::$app->controller;

        $c->postData = $data;
        $c->token = isset($data['token']) ? $data['token'] : '';
        unset($data['token']);
        return true;
    }
}