<?php
/**
 * Created by PhpStorm.
 * User: zhangzenan
 * Date: 2018/1/23
 * Time: 20:05
 */

namespace app\filters;


use app\controllers\BaseController;
use app\utils\Util;
use common\services\RedisService;

class DataFilter extends BaseFilter
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        $data = \Yii::$app->request->post()?:json_decode(file_get_contents("php://input"),true);
//
//        if (!isset($data['accessId']) || !isset($data['accessKey'])){
//            Util::renderJSON(-403, 'permission denied');
//        }
//        //初始化请求需要的参数
//        $this->accessId = $data['accessId'];
//        $this->accessKey = $data['accessKey'];
        $this->token = isset($data['token']) ? $data['token'] : '';
        unset($data['token']);
        var_dump($this->token);
        /** @var BaseController $c */
        $c = \Yii::$app->controller;

        $c->postData = $data;
        $c->token = $this->token;
        return true;
    }
}