<?php
/**
 * Created by PhpStorm.
 * User: zhangzenan
 * Date: 2018/1/23
 * Time: 19:44
 */

namespace app\filters;


use app\config\AppConfig;
use app\utils\Util;
use common\services\RedisService;

class UserFilter extends BaseFilter
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {

        $session = RedisService::hGet(AppConfig::userSession, $this->token);
        var_dump($this->token);exit;
        if(!isset($session)){
            Util::renderJSON(-401, '请登录');
        }

        $session = json_decode($session, true);
        if($session['ttl'] > time()){
            Util::renderJSON(-402, '请重新登录');
        }

        return true;
    }
}